version: '3.5'

services:
  dynamodb:
    image: amazon/dynamodb-local:1.11.477
    ports:
      - 8000:8000
    networks:
      - dynamodb
  init:
    image: datinc/awscli:20190509
    environment:
      - DYNAMODB_ENDPOINT_URL=http://dynamodb:8000
      - DYNAMODB_TABLES=table1;table2
    entrypoint: /app/create_table.sh
    volumes:
      - ./scripts:/app
    networks:
      - dynamodb

networks:
  dynamodb:
    driver: bridge

